In [1]:
import numpy as np
import pandas as pd

from claspy.data_loader import load_tssb_dataset, tssb_dataset_names
from statsmodels.tsa.stattools import adfuller, kpss

In [2]:
tssb = load_tssb_dataset()
tssb

dataset  window_size                      cps  \
0                  Adiac           10        [572, 1012, 1232]   
1              ArrowHead           10                    [753]   
2                   Beef           50                    [705]   
3              BeetleFly           10                   [1280]   
4            BirdChicken           20                   [1280]   
..                   ...          ...                      ...   
70  UWaveGestureLibraryX           10  [600, 1131, 1652, 2193]   
71  UWaveGestureLibraryY           10  [600, 1131, 1652, 2193]   
72  UWaveGestureLibraryZ           10  [600, 1131, 1652, 2193]   
73          WordSynonyms           10              [202, 2227]   
74                  Yoga           10                   [7295]   

                                          time_series  
0   [1.681146, 1.383394, 1.029389, 0.688386, 0.354...  
1   [-1.957721, -1.858082, -1.657983, -1.420794, -...  
2   [-0.380818, -0.352238, -0.295392, -0.225041, -...  
3   [1.114805, 0.774403, 0.477129, 0.115781, -0.24...  
4   [1.697714, 1.439032, 1.22287, 0.99708, 0.76479...  
..                                                ...  
70  [-0.889766, 0.722005, 0.869297, -0.553167, -0....  
71  [-1.523467, -0.106794, 0.190361, 0.979247, 0.3...  
72  [-0.527058, 0.416111, -0.524027, 0.41141, 0.12...  
73  [-1.183581, -0.514028, -0.480539, -0.394855, -...  
74  [-0.155803, -0.33899, -0.564977, -0.667323, -0...  

[75 rows x 4 columns]

In [3]:
def tssb_time_series(dataset):
    return tssb.loc[tssb.dataset == dataset].time_series.tolist()[0]

tssb_time_series("ArrowHead")

array([-1.957721, -1.858082, -1.657983, ..., -1.54761 , -1.722706,
       -1.855437], shape=(1506,))

There is no time series that is not stationary according to the Augmented-Dickey-Fuller test.

In [4]:
pvals = []
for ds in tssb_dataset_names:
    ts = tssb_time_series(ds)
    adf, p, *_ = adfuller(ts)
    pvals.append(p)
npp_adf = np.array(pvals)
np.any(npp_adf >= 0.05), npp_adf

(np.False_,
 array([8.91006717e-18, 0.00000000e+00, 3.81550798e-12, 7.98258246e-27,
        6.34465532e-28, 7.37042705e-28, 2.72743079e-23, 5.30336029e-14,
        0.00000000e+00, 0.00000000e+00, 8.24043827e-29, 0.00000000e+00,
        5.31330033e-29, 2.88998285e-29, 5.51897676e-28, 0.00000000e+00,
        4.59038439e-29, 6.51649128e-20, 5.78607807e-24, 2.75540332e-04,
        1.64543038e-23, 2.62324627e-15, 8.13639310e-30, 0.00000000e+00,
        5.16712519e-30, 0.00000000e+00, 0.00000000e+00, 3.99223874e-30,
        0.00000000e+00, 0.00000000e+00, 2.65738775e-22, 0.00000000e+00,
        3.55557211e-30, 0.00000000e+00, 3.63351091e-29, 1.90050671e-20,
        4.60533219e-20, 0.00000000e+00, 3.98095824e-18, 2.48922317e-25,
        2.25446351e-18, 1.68924957e-28, 4.57982302e-27, 0.00000000e+00,
        2.27127729e-30, 0.00000000e+00, 0.00000000e+00, 1.54528678e-15,
        0.00000000e+00, 0.00000000e+00, 4.07310504e-19, 5.99594815e-24,
        0.00000000e+00, 7.92624464e-30, 1.07687369e-

There is no time series that is not stationary according to the Kwiatkowski-Phillips-Schmidt-Shin test.


In [5]:
pvals = []
for ds in tssb_dataset_names:
    ts = tssb_time_series(ds)
    kpss_stat, p, *_ = kpss(ts)
    pvals.append(p)
npp_kpss = np.array(pvals)
np.all(npp_kpss >= 0.05), npp_kpss

/tmp/ipykernel_60653/1751065411.py:4: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  kpss_stat, p, *_ = kpss(ts)
/tmp/ipykernel_60653/1751065411.py:4: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  kpss_stat, p, *_ = kpss(ts)
/tmp/ipykernel_60653/1751065411.py:4: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  kpss_stat, p, *_ = kpss(ts)
/tmp/ipykernel_60653/1751065411.py:4: InterpolationWarning: The test statistic is outside of the range of p-values available in the
look-up table. The actual p-value is greater than the p-value returned.

  kpss_stat, p, *_ = kpss(ts)
/tmp/ipykernel_60653/1751065411.py:4: InterpolationWarning: 

(np.True_,
 array([0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
        0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
        0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
        0.1       , 0.1       , 0.07237248, 0.1       , 0.1       ,
        0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
        0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
        0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
        0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
        0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
        0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
        0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
        0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
        0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
        0.1       , 0.1       , 0.1       , 0.1       , 0.1       ,
        0.1       , 0.1       , 0.1  